source_destination_postgres:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: admin
      pass: admin
      dbname: source_postgres
      schema: public
  target: dev
